// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package initializers

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApplication(envFilePath string) (*ContextContainer, func(), error) {
	config, err := ProvideConfig(envFilePath)
	if err != nil {
		return nil, nil, err
	}
	db, err := ProvideGormDb(config)
	if err != nil {
		return nil, nil, err
	}
	serviceOptions := ProvideSvcOptions(db)
	client := ProvideMqttClient(config, serviceOptions)
	handlerOptions := ProvideHandlerOptions(serviceOptions, client)
	contextContainer := ProvideAppInfrastructure(config, db, client, handlerOptions)
	return contextContainer, func() {
	}, nil
}

// wire.go:

var ApplicationSet = wire.NewSet(
	ProvideConfig,
	ProvideGormDb,
	ProvideSvcOptions,
	ProvideMqttClient,
	ProvideHandlerOptions,
	ProvideAppInfrastructure,
)
